-- =============================================================================================
-- Gold deploy-time objects for the credit assistant (run on deploy, not daily):
--   fn_monthly_installment / fn_max_principal  annuity math shared with the rules service
--   credit_offers                               offers accepted in the chat (written by the API)
-- Idempotent: functions are replaced, credit_offers is created only if missing and never dropped.
-- Parameter :gold_schema (catalog.schema): _test or the real gold schema.
-- Policy and formulas: docs/CREDIT_RULES.md. Synthetic policy, offline results.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- Shared annuity math. The rules service must implement exactly these two formulas.
-- ---------------------------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS IDENTIFIER(:gold_schema);

CREATE OR REPLACE FUNCTION IDENTIFIER(:gold_schema || '.fn_monthly_installment')(
    principal DOUBLE, annual_rate_pct DOUBLE, term_months INT)
RETURNS DOUBLE
COMMENT 'Fixed monthly installment of an annuity loan: P * r / (1 - (1 + r)^-n), r = annual_rate_pct / 1200'
RETURN CASE
    WHEN principal IS NULL OR principal <= 0 OR term_months IS NULL OR term_months <= 0 THEN 0
    WHEN coalesce(annual_rate_pct, 0) = 0 THEN principal / term_months
    ELSE principal * (annual_rate_pct / 1200) / (1 - pow(1 + annual_rate_pct / 1200, -term_months))
END;

CREATE OR REPLACE FUNCTION IDENTIFIER(:gold_schema || '.fn_max_principal')(
    monthly_installment DOUBLE, annual_rate_pct DOUBLE, term_months INT)
RETURNS DOUBLE
COMMENT 'Largest principal a monthly installment can repay: I * (1 - (1 + r)^-n) / r, r = annual_rate_pct / 1200'
RETURN CASE
    WHEN monthly_installment IS NULL OR monthly_installment <= 0 OR term_months IS NULL OR term_months <= 0 THEN 0
    WHEN coalesce(annual_rate_pct, 0) = 0 THEN monthly_installment * term_months
    ELSE monthly_installment * (1 - pow(1 + annual_rate_pct / 1200, -term_months)) / (annual_rate_pct / 1200)
END;

-- ---------------------------------------------------------------------------------------------
-- credit_offers: offers the customer accepted in the chat, before the advisor handoff.
-- Written only by the API / rules service (never by the LLM). One row per accepted offer;
-- later changes update status. Not rebuilt: CREATE IF NOT EXISTS keeps the history.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDENTIFIER(:gold_schema || '.credit_offers') (
    offer_id                   STRING        NOT NULL COMMENT 'Unique offer id generated by the rules service (UUID)',
    customer_id                STRING        NOT NULL COMMENT 'Customer, taken from the session token, never from LLM text',
    session_id                 STRING                 COMMENT 'Chat session id',
    channel                    STRING                 COMMENT 'Channel where the offer was accepted, e.g. chat',
    language                   STRING                 COMMENT 'Conversation language: es or pt',
    offer_origin               STRING        NOT NULL COMMENT 'proactive (customer accepts marketing) or customer_interest (customer asked in the chat)',
    -- what was offered
    option_code                STRING        NOT NULL COMMENT 'ref_term_grid option: PL, MG or CC-<tier>',
    product_code               STRING        NOT NULL COMMENT 'CC, PL or MG',
    product_type               STRING        NOT NULL COMMENT 'Credit Card, Personal Loan or Mortgage',
    tier                       STRING                 COMMENT 'Card tier; null for loans',
    term_months                INT           NOT NULL COMMENT 'Term in months',
    amount_usd                 DOUBLE        NOT NULL COMMENT 'Accepted amount or credit limit in USD',
    annual_rate_pct            DOUBLE        NOT NULL COMMENT 'Offered nominal annual rate, percent',
    monthly_installment_usd    DOUBLE        NOT NULL COMMENT 'Monthly installment in USD',
    local_currency             STRING        NOT NULL COMMENT 'MXN, COP or ARS',
    fx_to_usd                  DOUBLE        NOT NULL COMMENT 'Exchange rate used: 1 local unit = fx_to_usd USD',
    fx_date                    DATE                   COMMENT 'Date of the exchange rate used',
    amount_local               DOUBLE        NOT NULL COMMENT 'Accepted amount in local currency, as shown to the customer',
    monthly_installment_local  DOUBLE        NOT NULL COMMENT 'Monthly installment in local currency, as shown to the customer',
    -- how it was computed
    income_used_usd            DOUBLE        NOT NULL COMMENT 'Monthly income used for the 20% limit',
    income_source              STRING        NOT NULL COMMENT 'declared_profile or declared_in_chat',
    current_installments_usd   DOUBLE        NOT NULL COMMENT 'Existing monthly installments, including external debt declared in chat',
    max_total_installment_usd  DOUBLE        NOT NULL COMMENT 'max_debt_to_income x income_used_usd',
    debt_to_income_after       DOUBLE        NOT NULL COMMENT '(current installments + new installment) / income; must be <= max_debt_to_income',
    risk_band                  STRING        NOT NULL COMMENT 'Band at offer time',
    segment                    STRING                 COMMENT 'Customer segment at offer time',
    rate_adjustment_pp         DOUBLE        NOT NULL COMMENT 'Total band + segment adjustment applied to the reference rate',
    customer_declared_data     STRING                 COMMENT 'JSON with data the customer gave in the chat (income, household income, external debts)',
    -- complaint context at offer time, recorded for the advisor
    open_complaints            INT           NOT NULL COMMENT 'Open complaints (Open, In Process, Escalated) at offer time',
    open_priority_complaints   INT           NOT NULL COMMENT 'Open High or Critical complaints at offer time',
    open_critical_complaints   INT           NOT NULL COMMENT 'Open Critical complaints at offer time; > 0 means the offer was not proactive',
    -- controls and handoff
    is_conditional             BOOLEAN       NOT NULL COMMENT 'True when the offer relies on data declared in the chat',
    flags                      ARRAY<STRING>          COMMENT 'Advisor flags: F02_NEAR_LIMIT_DECLARED_INCOME, F03_DECLARED_DATA, F04_OPEN_COMPLAINTS',
    required_documents         ARRAY<STRING>          COMMENT 'Documents the advisor must request',
    status                     STRING        NOT NULL COMMENT 'accepted, handed_off, expired or cancelled',
    handoff_ticket_id          STRING                 COMMENT 'Advisor queue ticket once handed off',
    advisor_summary            STRING                 COMMENT 'Summary sent to the advisor',
    valid_until                DATE          NOT NULL COMMENT 'Offer expiry (offer_validity_days after acceptance)',
    profile_as_of_date         DATE          NOT NULL COMMENT 'as_of_date of the profile used',
    policy_version             STRING        NOT NULL COMMENT 'Policy parameters version used',
    created_at                 TIMESTAMP     NOT NULL COMMENT 'When the customer accepted',
    updated_at                 TIMESTAMP              COMMENT 'Last status change',
    CONSTRAINT credit_offers_pk PRIMARY KEY (offer_id)
)
COMMENT 'Offers accepted by customers in the chat, pending or after advisor handoff. Every accepted offer goes to an advisor, who verifies documents and decides. Written by the API/rules service only.'
TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true');

ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') DROP CONSTRAINT IF EXISTS valid_status;
ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') ADD CONSTRAINT valid_status
    CHECK (status IN ('accepted', 'handed_off', 'expired', 'cancelled'));

ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') DROP CONSTRAINT IF EXISTS valid_offer_origin;
ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') ADD CONSTRAINT valid_offer_origin
    CHECK (offer_origin IN ('proactive', 'customer_interest'));

ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') DROP CONSTRAINT IF EXISTS positive_amounts;
ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') ADD CONSTRAINT positive_amounts
    CHECK (amount_usd > 0 AND monthly_installment_usd > 0 AND income_used_usd > 0);

-- Guardrail duplicating ref_policy_params.max_debt_to_income: update it if that parameter changes.
ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') DROP CONSTRAINT IF EXISTS within_debt_limit;
ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') ADD CONSTRAINT within_debt_limit
    CHECK (debt_to_income_after <= 0.20 + 1e-9);

-- Keep column comments current on an existing table (CREATE TABLE IF NOT EXISTS does not update them).
ALTER TABLE IDENTIFIER(:gold_schema || '.credit_offers') ALTER COLUMN flags
    COMMENT 'Advisor flags: F02_NEAR_LIMIT_DECLARED_INCOME, F03_DECLARED_DATA, F04_OPEN_COMPLAINTS';
